### ISSUE TITLE
Loop closure doesn't fix the Z-axis drift. Any ideas?

### ISSUE THREAD

**Issue by se7oluti0n** [koide3/glim#108]
Hello,

First of all, thank you for the contribution.
I have tested mapping on 1 round of the Park near my house. The park size is about 500m x 280m. 
I the the elevation of the Park is almost the same, some point on the trajectory has higher elevation, few meter.

For the map, there is one loop closure because I went 1 round of the park. I used offline viewer to create manual factor.
But the final map after the loop-closure show huge different of elevation **(about 30 meter)** at two side of the park?

Any ideas to improve the z-drift after loop closure?

![Screenshot from 2024-11-07 09-38-25](https://github.com/user-attachments/assets/2056a381-ed3c-416e-ad19-c81439a1036e)
![Screenshot from 2024-11-07 09-38-01](https://github.com/user-attachments/assets/0f03dc29-cb02-4c7e-8c1b-8e8a8d4dcf40)

**Comment by tahakenar** [comment]
Hi, 
I am also facing the same issue with a relatively small map (~20m x ~170m road). I minimized cumulative Z-drift by manually closing the loop. Yet, there is still difference in Z axis between two ends of the map.

I provide the screenshots below. With no loop closure, Z-drift after closure and final map after loop closure respectively.

![z-drift](https://github.com/user-attachments/assets/b6f439e0-134c-43d2-9515-7c2f04661943)
![glim-drift-loop-closed](https://github.com/user-attachments/assets/26a8aed7-766b-4e98-940f-73901cdaf75d)
![glim-loop-closed](https://github.com/user-attachments/assets/02c7deb0-a408-4ac0-9495-4236269c00ab)

**Comment by se7oluti0n** [comment]
@tahakenar Thank for the information. One thing that is similar in our cases is we both traveled in a quite narrow road with the high tree at the sides at some points. May that case cause the error in the pitch angle estimation and lead to the z drift, I guess.

**Comment by tahakenar** [comment]
@se7oluti0n I processed my bag file to filter out point cloud data.  I clamped points using boundaries -15m to 15m for x and y. In z axis I clamped between -1.5m to 2.5m. Seems like it yields better results in terms of z-axis drift.

Before finding overlapping submaps and manual loop closure:

![glim-clamped-no-loop-closure](https://github.com/user-attachments/assets/a5d6f6d1-af32-499c-9442-39eb8c50a3d2)

After manual loop closure and finding overlapping submaps:

![glim-final](https://github.com/user-attachments/assets/328fc6e5-b32b-460c-a70c-4f077989a507)

![flat](https://github.com/user-attachments/assets/3758ed91-8424-4390-a4ca-a1e5e3c7370b)

**Comment by skohlbr** [comment]
Depends on the use case, but the https://github.com/koide3/glim_ext?tab=readme-ov-file#flat-earther plugin might solve this issue if the environment is approximately flat.

**Comment by koide3** [comment]
Yes, the [flat_earther plugin](https://github.com/koide3/glim_ext?tab=readme-ov-file#flat-earther) should solve the issue. In particular, if your environment is approximately flat overall, setting `max_neighbor_distance` in `config_flat_earther.json` to a large value (e.g., 1000 m) forces the map to be flat.

**Comment by se7oluti0n** [comment]
@skohlbr @koide3 Thanks for the suggestion. Closed topic here.
