### ISSUE TITLE
ROS1 catkin build error report

### ISSUE THREAD

**Issue by JongRok-Lee** [koide3/glim#114]
**Describe the bug**
When building with catkin_make, there are no issues, but when using the `catkin build` command, the following error occurs, and the `glim_ros1` build fails.

**To Reproduce**
``` bash
cd ~/ws
catkin build
```

**Screenshots**
![image](https://github.com/user-attachments/assets/7ee67912-dec8-4a7d-a9fe-0f87a3047da9)
``` bash
// line 17
find_package(glim REQUIRED)
```
**Environment (please complete the following information):**
 - CPU/GPU: i9-9900K/RTX4090]
 - OS: Ubuntu 20.04
 - ROS: ROS1 noetic
 - CUDA: 11.8
 - Build with CUDA: OFF

In ROS1, catkin build is commonly used for building rather than catkin_make, so it would be great if there is a way to build using catkin build.
I have spent 4 hours trying to resolve this issue but was unable to find a solution, so I am reporting this issue. Thank you.

**Comment by koide3** [comment]
To my understanding, `catkin build` builds packages independently, resulting in dependency issues. While it should be resolved with minor modifications, I'm not keen to do it as ROS1 is mostly outdated (Any PR from the community will be appreciated). I think building `glim` and `glim_ros` in another workspace with `catkin_make` could be a workaround.
