### ISSUE TITLE
IMU Initialization

### ISSUE THREAD

**Issue by rafaelspring** [koide3/glim#23]
Hi Kenji, amazing project! Congratulations on the release!

I have a question: many popular visual SLAM methods (e.g. ORB-SLAM 3) have an IMU-initialization stage to get initial estimates for the initial gravity vector, initial velocities and IMU biases.
I haven't found anything similar in the GLIM paper or in the code.

Is there an initialization stage that I missed?
Or is GLIM making certain assumptions on the initial state and biases?

Kind regards,
Rafael

**Comment by koide3** [comment]
There is [a loose coupling-based initial state estimation](https://github.com/koide3/glim/blob/master/src/glim/odometry/loose_initial_state_estimation.cpp) adopted from our following paper.

Tightly Coupled Range Inertial Localization on a 3D Prior Map Based on Sliding Window Factor Graph Optimization, ICRA2024

**Comment by rafaelspring** [comment]
Thanks! I'll check it out.

**Comment by hunkyu** [comment]
@koide3 Tightly Coupled Range Inertial Localization on a 3D Prior Map Based on Sliding Window Factor Graph Optimization, ICRA2024 Will this part of the work be open source? Is it part of glim?

**Comment by koide3** [comment]
The initialization algorithm is included in GLIM. The map-based localization algorithm will not be included.

**Comment by rafaelspring** [comment]
Thanks, got it!

**Comment by LitoNeo** [comment]
Great work! Thanks!
