### ISSUE TITLE
complie error

### ISSUE THREAD

**Issue by ZOUJIASHUAI** [koide3/glim#29]
--------------------------------------------------------
Profile:                     default
Extending:          [cached] /opt/ros/melodic
Workspace:                   /home/jason/glim_ws
--------------------------------------------------------
Build Space:        [exists] /home/jason/glim_ws/build
Devel Space:        [exists] /home/jason/glim_ws/devel
Install Space:      [unused] /home/jason/glim_ws/install
Log Space:          [exists] /home/jason/glim_ws/logs
Source Space:       [exists] /home/jason/glim_ws/src
DESTDIR:            [unused] None
--------------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        None
--------------------------------------------------------
Additional CMake Args:       -DCMAKE_BUILD_TYPE=Release
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
--------------------------------------------------------
Buildlisted Packages:        None
Skiplisted Packages:         None
--------------------------------------------------------
Workspace configuration appears valid.
--------------------------------------------------------
[build] Found 1 packages in 0.0 seconds.                                       
[build] Package table is up to date.                                           
Starting  >>> glim                                                             
_______________________________________________________________________________
Errors     << glim:cmake /home/jason/glim_ws/logs/glim/build.cmake.001.log     
CMake Error at CMakeLists.txt:28 (find_package):
  By not providing "Findgtsam_points.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "gtsam_points", but CMake did not find one.

  Could not find a package configuration file provided by "gtsam_points" with
  any of the following names:

    gtsam_pointsConfig.cmake
    gtsam_points-config.cmake

  Add the installation prefix of "gtsam_points" to CMAKE_PREFIX_PATH or set
  "gtsam_points_DIR" to a directory containing one of the above files.  If
  "gtsam_points" provides a separate development package or SDK, be sure it
  has been installed.

cd /home/jason/glim_ws/build/glim; catkin build --get-env glim | catkin env -si  /usr/local/bin/cmake /home/jason/glim_ws/src/glim --no-warn-unused-cli -DCATKIN_DEVEL_PREFIX=/home/jason/glim_ws/devel/.private/glim -DCMAKE_INSTALL_PREFIX=/home/jason/glim_ws/install -DCMAKE_BUILD_TYPE=Release; cd -

...............................................................................
Failed     << glim:cmake          [ Exited with code 1 ]                       
Failed    <<< glim                [ 0.1 seconds ]                              
[build] Summary: 0 of 1 packages succeeded.                                    
[build]   Ignored:   None.                                                     
[build]   Warnings:  None.                                                     
[build]   Abandoned: None.                                                     
[build]   Failed:    1 packages failed.                                        
[build] Runtime: 0.2 seconds total.

**Comment by South-River** [comment]
you should follow the docs and build and install gtsam_points package in advance
