### ISSUE TITLE
warning: cudaErrorInsufficientDriver: CUDA driver version is insufficient for CUDA runtime version

### ISSUE THREAD

**Issue by gityeezy** [koide3/glim#31]
Hello, you did a great job. But when I was implementing the code, I encountered the problem of 'CUDA driver version is insufficient for CUDA runtime version'. My environment is using my ubuntu20.04 docker, using eigen3.4.0, cuda12.2.2, then following your tutorial to install gtsam, iridescence, gtsampoints, and finally using ros1 to encode the code. Although there were some problems in the middle, I solved them and the compilation passed. However, when I used the rosrun command, I started reporting errors. If I force run the bag package, it will be directly aborted. How should I find the problem?

![2024-07-21 19-17-21 的屏幕截图](https://github.com/user-attachments/assets/516168d2-5477-462a-ab9f-1a67c522ee2d)
![2024-07-21 19-17-43 的屏幕截图](https://github.com/user-attachments/assets/5fbff438-f50a-410b-b927-59478935f521)

**Comment by South-River** [comment]
in my opinion, that's might because your gpu driver is too low that in sufficient for CUDAToolKit 12.2.2, maybe you should check your GPU driver and update it.

**Comment by koide3** [comment]
As @South-River said, it might stem from your nvidia driver version. Check the driver version with `nvidia-smi`.

**Comment by gityeezy** [comment]
Thank you, I have solved this problem. It is not because my driver version is too low or wrong, my driver is the latest, and my GPU supports cuda12.2. It is because my GPU computing power is 86, but during my compilation process, I set it to 89 by mistake, so the error is reported.
