### ISSUE TITLE
Doc update required

### ISSUE THREAD

**Issue by changh95** [koide3/glim#33]
Thank you for making a great contribution to the robotics community! :+1: 

---

In the document website, it is shown as the image below: (https://koide3.github.io/glim/docker.html)

- `Launch glim_ros:noetic... ` whilst the command actually mentions ROS2 humble.

![image](https://github.com/user-attachments/assets/4916c087-b196-4610-9cf1-c3bd4ccdab3f)

But we see that the doc source file has already been updated. (https://github.com/koide3/glim/blob/master/docs/docker.md#with-gpu)

![image](https://github.com/user-attachments/assets/c2b37a94-ae54-4a05-b10e-5b2f8ffabd00)

---

This means the GitHub Actions for the gendoc has not run yet.

Triggering GitHub Actions requires admin previleges.

Please run the Actions to update the docs webpage.

**Comment by koide3** [comment]
Thanks for reporting the issue. The CI for doc update will be triggered once the next tag is pushed. I'm finalizing some updates to be included in the next release and will push it in a few days.
