### ISSUE TITLE
Cannot open dump results with Offline Viewer with ROS

### ISSUE THREAD

**Issue by DeriZSY** [koide3/glim#45]
Hi, thanks for the great work. I'm using the docker image you provided, the demo is working fine and generated dumped correctly. 

But when I was trying to use the Offline Viewer, I found it doesn't work. To be exact, nothing happened after I clicked "Open Map" (no logs), and as I clicked "Export Points" it indeed told me there's nothing to export (which means the viewer itself is running correctly).

**Comment by koide3** [comment]
That should be fixed by installing `zenity`. I'll fix the dockerfiles soon.

https://github.com/koide3/glim/issues/36#issuecomment-2244348365

**Comment by koide3** [comment]
`zenity` is added to the dockerfiles, and updated images are now available on docker hub https://github.com/koide3/glim_ros2/pull/14
