### ISSUE TITLE
Suggestions for Surface Reconstruction

### ISSUE THREAD

**Issue by Edwardius** [koide3/glim#46]
Hello, 

I'm looking to convert GLIM's outputted .ply file into a triangular mesh. Does anyone have any suggestions for 3D tools that can do this? 

Thanks!

**Comment by koide3** [comment]
There are some software like Leica cyclone that supports mesh generation from point cloud. Meanwhile, I recommend using mapping algorithms like [wavemap](https://github.com/ethz-asl/wavemap) that can use raw point cloud frames as input rather than an accumulated point cloud.

**Comment by Edwardius** [comment]
Cool thanks
