### ISSUE TITLE
run time error with cuda 12.6

### ISSUE THREAD

**Issue by zhangzscn** [koide3/glim#73]
ubuntu 22.04
cuda 12.6

ros2 run glim_ros glim_rosbag os1_128_01
/mnt/b/glim/install/glim_ros/lib/glim_ros/glim_rosbag: symbol lookup error: /usr/local/lib/libgtsam_points_cuda.so: undefined symbol: _ZNK5gtsam15NonlinearFactor5rekeyERKSt6vectorImSaImEE
[ros2run]: Process exited with failure 127

**Comment by zhangzscn** [comment]
cuda 12.5 also the same error

**Comment by koide3** [comment]
A similar error happens when GTSAM was rebuilt with different options. Can you try to clean install GTSAM and gtsam_points? I also recommend try installing PPA packages without building them by yourself.

https://koide3.github.io/glim/installation.html

**Comment by zhangzscn** [comment]
sudo apt install -y libgtsam-points-cuda-12.5-dev
正在读取软件包列表... 完成
正在分析软件包的依赖关系树... 完成
正在读取状态信息... 完成                 
E: 无法定位软件包 libgtsam-points-cuda-12.5-dev
E: 无法按照 glob ‘libgtsam-points-cuda-12.5-dev’ 找到任何软件包

**Comment by zhangzscn** [comment]
I also try to clean install GTSAM and gtsam_points,but it do not work

**Comment by zhangzscn** [comment]
sorry, I git clone the gtsam,gtsam_points to the ros2_ws ,this make the error.just remove them form ros2_ws, solve the error
