### ISSUE TITLE
How can I use my lidar in this project?

### ISSUE THREAD

**Issue by JiangWeiHn** [koide3/glim#78]
My lidar is Robosense -16。How can i define the lidar type in the confige？And Which part of the program should I modify the code to adapt to My lidar type? I look forward to your reply，thanks a lot.

**Comment by koide3** [comment]
Please take a look at [the setup guide](https://github.com/koide3/glim/wiki/Sensor-setup-guide). The configuration for VLP16 would be helpful for you.

**Comment by JiangWeiHn** [comment]
thanks for reply.
