### ISSUE TITLE
Localization only mode?

### ISSUE THREAD

**Issue by lisosia** [koide3/glim#84]
Is it possible to run glim in a localization only mode as follows:
1. After creating the map, save the map and exit.
2. Load the map and perform localization only (no map update).

I plan to use glim with MID-360.
Sorry if this is a strange question.

Thanks.

**Comment by koide3** [comment]
We have another package GLIL for prior-map-based localization, but it's closed source requiring a proprietary license.

**Comment by lisosia** [comment]
I got it. Thank you for your answer!

**Comment by zhoubo2018** [comment]
> We have another package GLIL for prior-map-based localization, but it's closed source requiring a proprietary license.

Hello,how to get this closed source? Can you give me some introduction about that(GLIL) localization system?
