### ISSUE TITLE
Reducing weight of the IntegratedVGICPFactorGPU factor?

### ISSUE THREAD

**Issue by zMkOrg** [koide3/glim#90]
Hi, thank you for sharing this great work. 
I want to reduce the weight of the IntegratedVGICPFactorGPU factor so I can integrate data from other high precision sensors. Could you tell me how to do this? I would be very grateful. I didn't see any function interfaces in gtsam_points for reducing weight or increasing noise.

**Comment by koide3** [comment]
While gtsam_points doesn't have a direct interface to do it, you can change the matching weight by increasing the covariance of each point (`Frame::covs`).

**Comment by zMkOrg** [comment]
it worked! thank you for your kind help and immediate response.

> While gtsam_points doesn't have a direct interface to do it, you can change the matching weight by increasing the covariance of each point (`Frame::covs`).
